# Generated by Django 4.2.14 on 2025-07-27 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_artists', to='STARS.artist'),
        ),
        migrations.AlterField(
            model_name='projectartist',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_artists', to='STARS.project'),
        ),
        migrations.AlterField(
            model_name='projectsong',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_songs', to='STARS.project'),
        ),
        migrations.AlterField(
            model_name='projectsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_songs', to='STARS.song'),
        ),
        migrations.AlterField(
            model_name='songartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artists', to='STARS.artist'),
        ),
        migrations.AlterField(
            model_name='songartist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artists', to='STARS.song'),
        ),
    ]
