# Generated by Django 5.2.4 on 2025-07-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='preview_url',
            new_name='preview',
        ),
    ]
