# Generated by Django 5.2.4 on 2025-07-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stars', '0002_rename_preview_url_song_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='songs',
        ),
        migrations.CreateModel(
            name='ProjectSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stars.project')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Stars.song')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('project', 'song')},
            },
        ),
    ]
