# Generated by Django 5.2.4 on 2025-07-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stars', '0003_remove_project_songs_projectsong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Stars',
            new_name='stars',
        ),
        migrations.RenameField(
            model_name='subreview',
            old_name='Stars',
            new_name='stars',
        ),
    ]
