# Generated by Django 5.2.5 on 2025-08-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0004_comment_disliked_by_comment_dislikes_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='featured_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cover',
            name='featured_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='featured_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='featured_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='musicvideo',
            name='featured_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='outfit',
            name='featured_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='featured_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='featured_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='song',
            name='featured_message',
            field=models.TextField(blank=True),
        ),
    ]
