# Generated by Django 5.2.4 on 2025-07-20 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0004_rename_stars_review_stars_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artists',
        ),
        migrations.CreateModel(
            name='ProjectArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STARS.artist')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STARS.project')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('project', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='SongArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STARS.artist')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='STARS.song')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('song', 'artist')},
            },
        ),
    ]
