# Generated by Django 5.2.4 on 2025-07-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0005_remove_project_artists_remove_song_artists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideo',
            name='thumbnail',
            field=models.URLField(default='what', max_length=500),
            preserve_default=False,
        ),
    ]
