# Generated by Django 5.2.5 on 2025-08-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0005_artist_featured_message_cover_featured_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cover',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='cover',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
