# Generated by Django 5.2.5 on 2025-08-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0006_alter_cover_options_cover_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-time']},
        ),
    ]
