# Generated by Django 5.2.4 on 2025-07-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0006_musicvideo_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
