# Generated by Django 5.2.4 on 2025-07-24 15:37

import STARS.models
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0007_remove_message_receiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=django_choices_field.fields.TextChoicesField(choices=[('album', 'Album'), ('ep', 'EP'), ('mixtape', 'Mixtape'), ('single', 'Single')], choices_enum=STARS.models.ProjectCategory, db_index=True, max_length=7),
        ),
    ]
