# Generated by Django 5.2.5 on 2025-08-16 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0007_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_pending',
        ),
    ]
