# Generated by Django 5.2.4 on 2025-07-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0008_alter_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='star_average',
            field=models.FloatField(default=0),
        ),
    ]
