# Generated by Django 5.2.5 on 2025-08-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0008_remove_message_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='cover',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
