# Generated by Django 5.2.4 on 2025-07-24 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0009_event_reviews_count_event_star_average'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicvideo',
            old_name='releaseDate',
            new_name='release_date',
        ),
    ]
