# Generated by Django 5.2.5 on 2025-08-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0009_cover_primary_color_cover_secondary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideo',
            name='number_of_songs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicvideo',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='musicvideo',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
