# Generated by Django 5.2.5 on 2025-08-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0010_musicvideo_number_of_songs_musicvideo_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicvideo',
            name='youtube',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
