# Generated by Django 5.2.4 on 2025-07-24 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0010_rename_releasedate_musicvideo_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicvideo',
            old_name='youtubeURL',
            new_name='youtube_URL',
        ),
    ]
