# Generated by Django 5.2.4 on 2025-07-24 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0011_rename_youtubeurl_musicvideo_youtube_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musicvideo',
            old_name='youtube_URL',
            new_name='youtube',
        ),
    ]
