# Generated by Django 5.2.5 on 2025-08-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0011_alter_musicvideo_youtube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-latest_message_time']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='musicvideo',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterModelOptions(
            name='outfit',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={'ordering': ['-since']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-release_date']},
        ),
        migrations.AlterModelOptions(
            name='subreview',
            options={'ordering': ['position']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='accent_color_hex',
            new_name='custom_secondary_color',
        ),
        migrations.AddField(
            model_name='artist',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='artist',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='conversation',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='outfit',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner_picture_primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner_picture_secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_primary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture_secondary_color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='subreview',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='musicvideo',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
