# Generated by Django 5.2.5 on 2025-08-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0012_alter_comment_options_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['time']},
        ),
    ]
