# Generated by Django 5.2.4 on 2025-07-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0012_rename_youtube_url_musicvideo_youtube'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='accentColorHex',
            new_name='accent_color_hex',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='bannerPicture',
            new_name='banner_picture',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='followersCount',
            new_name='followers_count',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='followingCount',
            new_name='following_count',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='hasPremium',
            new_name='has_premium',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profilePicture',
            new_name='profile_picture',
        ),
    ]
