# Generated by Django 5.2.5 on 2025-08-26 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0013_alter_message_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='seen_by',
            field=models.ManyToManyField(blank=True, related_name='seen_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
