# Generated by Django 5.2.5 on 2025-09-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0014_conversation_seen_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
