# Generated by Django 5.2.5 on 2025-09-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0015_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='number_of_replies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='replying_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='STARS.comment'),
        ),
    ]
