# Generated by Django 5.2.5 on 2025-09-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0016_comment_number_of_replies_comment_replying_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
