# Generated by Django 5.2.5 on 2025-09-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0017_review_comments_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_picture',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
