# Generated by Django 5.2.5 on 2025-09-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0018_alter_profile_banner_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
