# Generated by Django 5.2.5 on 2025-10-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0019_alter_profile_banner_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='apple_music_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='apple_music_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='apple_music_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
