# Generated by Django 5.2.5 on 2025-11-27 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0020_artist_apple_music_id_project_apple_music_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnresolvedImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('DEDUPLICATION', 'Song Deduplication'), ('FEATURE_RESOLUTION', 'Feature Resolution')], max_length=50)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('resolution_payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING_USER', 'Awaiting User Resolution'), ('PENDING_ADMIN', 'Awaiting Admin Review'), ('RESOLVED', 'Task Completed')], db_index=True, default='PENDING_USER', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('admin_note', models.TextField(blank=True)),
                ('importer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_tasks', to=settings.AUTH_USER_MODEL)),
                ('partial_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='STARS.project')),
            ],
        ),
    ]
