# Generated by Django 5.2.5 on 2025-12-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0021_unresolvedimporttask'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, unique=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('featured_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='length',
        ),
        migrations.AddField(
            model_name='project',
            name='record_label',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='genres',
            field=models.ManyToManyField(related_name='projects', to='STARS.musicgenre'),
        ),
        migrations.AddField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(related_name='songs', to='STARS.musicgenre'),
        ),
    ]
