# Generated by Django 5.2.5 on 2025-12-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0022_musicgenre_remove_project_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='artists', to='STARS.musicgenre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='projects', to='STARS.musicgenre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='songs', to='STARS.musicgenre'),
        ),
    ]
