# Generated by Django 5.2.5 on 2025-12-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0023_artist_genres_alter_project_genres_alter_song_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsong',
            name='disc_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
