# Generated by Django 5.2.5 on 2025-12-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0024_projectsong_disc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
