# Generated by Django 5.2.5 on 2025-12-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0025_project_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='apple_music',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='bandcamp',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='deezer',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='soundcloud',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='spotify',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='tidal',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_music',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
