# Generated by Django 5.2.5 on 2025-12-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0026_song_apple_music_song_bandcamp_song_deezer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideo',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
