# Generated by Django 5.2.5 on 2025-12-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0027_musicvideo_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_out',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
