# Generated by Django 5.2.5 on 2025-12-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0028_song_is_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicvideo',
            name='channel_name',
            field=models.CharField(db_index=True, default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musicvideo',
            name='length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
