# Generated by Django 5.2.5 on 2025-12-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0029_musicvideo_channel_name_musicvideo_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('channel_name', models.CharField(db_index=True, max_length=500)),
                ('number_of_songs', models.IntegerField()),
                ('release_date', models.DateField(db_index=True)),
                ('length', models.IntegerField()),
                ('youtube', models.URLField(max_length=500, unique=True)),
                ('thumbnail', models.URLField(blank=True, max_length=500, null=True)),
                ('reviews_count', models.IntegerField(default=0)),
                ('star_average', models.FloatField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('featured_message', models.TextField(blank=True)),
                ('primary_color', models.CharField(blank=True, max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7)),
                ('songs', models.ManyToManyField(related_name='performance_videos', to='STARS.song')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
