# Generated by Django 5.2.5 on 2025-12-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0030_performancevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='performance_video_reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
