# Generated by Django 5.2.5 on 2025-12-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0031_profile_performance_video_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancevideo',
            name='performance_type',
            field=models.CharField(choices=[('AWARD_SHOW', 'Award Show'), ('TOUR', 'Tour'), ('FESTIVAL', 'Festival'), ('TV_APPEARANCE', 'TV Appearance'), ('LIVE_SESSION', 'Live Session'), ('RESIDENCY', 'Residency'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
    ]
