# Generated by Django 5.2.5 on 2025-12-27 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0032_performancevideo_performance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancevideo',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performances', to='STARS.event'),
        ),
    ]
