# Generated by Django 5.2.5 on 2025-12-28 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0033_performancevideo_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancevideo',
            name='artists',
            field=models.ManyToManyField(related_name='performance_videos', to='STARS.artist'),
        ),
        migrations.AlterField(
            model_name='performancevideo',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_videos', to='STARS.event'),
        ),
    ]
