# Generated by Django 5.2.5 on 2025-12-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0034_performancevideo_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='hosts',
        ),
        migrations.AddField(
            model_name='podcast',
            name='apple_podcasts_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='host',
            field=models.CharField(db_index=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
