# Generated by Django 5.2.5 on 2025-12-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0035_remove_podcast_hosts_podcast_apple_podcasts_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500, unique=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('featured_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='podcast',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='podcasts', to='STARS.podcastgenre'),
        ),
    ]
