# Generated by Django 5.2.5 on 2026-01-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0036_podcastgenre_podcast_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performancevideo',
            name='performance_type',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('AWARD_SHOW', 'Award Show'), ('TOUR', 'Tour'), ('FESTIVAL', 'Festival'), ('TV_APPEARANCE', 'TV Appearance'), ('LIVE_SESSION', 'Live Session'), ('RESIDENCY', 'Residency'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='series_type',
            field=models.CharField(choices=[('AWARD_SHOW', 'Award Show'), ('TOUR', 'Tour'), ('FESTIVAL', 'Festival'), ('TV_APPEARANCE', 'TV Appearance'), ('LIVE_SESSION', 'Live Session'), ('RESIDENCY', 'Residency'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20),
        ),
    ]
