# Generated by Django 5.2.5 on 2026-01-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0039_searchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
