# Generated by Django 5.2.5 on 2026-01-10 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0040_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='musicvideo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='outfit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='performancevideo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='podcast',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
    ]
