# Generated by Django 5.2.5 on 2026-01-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0041_alter_comment_options_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='apple_podcasts_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
