# Generated by Django 5.2.5 on 2026-01-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0042_alter_podcast_apple_podcasts_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cover',
            name='image',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='musicvideo',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='performancevideo',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='apple_music_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='apple_music_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
