# Generated by Django 5.2.5 on 2026-01-17 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0043_alter_cover_image_alter_musicvideo_youtube_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectsong',
            options={'ordering': ['disc_number', 'position']},
        ),
    ]
