# Generated by Django 5.2.5 on 2026-01-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0044_alter_projectsong_options'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cover',
            options={},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_created']},
        ),
        migrations.RemoveField(
            model_name='artist',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='project',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genres',
        ),
        migrations.AddField(
            model_name='artist',
            name='covers_star_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='music_videos_star_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='outfits_star_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='performances_star_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='projects_star_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='songs_star_average',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='star_average',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subreview',
            name='topic',
            field=models.CharField(choices=[('LYRICS', 'Lyrics'), ('PRODUCTION', 'Production'), ('COLOR_PALETTE', 'Color Palette'), ('DIRECTION', 'Direction'), ('VOCAL_PERFORMANCE', 'Vocal Performance'), ('STYLING', 'Styling')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='cover',
            unique_together={('content_type', 'object_id', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='projectartist',
            unique_together={('project', 'artist'), ('project', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='projectsong',
            unique_together={('project', 'disc_number', 'position'), ('project', 'song')},
        ),
        migrations.AlterUniqueTogether(
            name='songartist',
            unique_together={('song', 'artist'), ('song', 'position')},
        ),
        migrations.AddField(
            model_name='review',
            name='ranked_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='STARS.rankedlist'),
        ),
        migrations.CreateModel(
            name='ArtistGenresOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_genres_ordered', to='STARS.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_genres_ordered', to='STARS.musicgenre')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('artist', 'genre'), ('artist', 'position')},
            },
        ),
        migrations.CreateModel(
            name='PodcastGenresOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_genres_ordered', to='STARS.podcastgenre')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast_genres_ordered', to='STARS.podcast')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('podcast', 'genre'), ('podcast', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ProjectGenresOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_genres_ordered', to='STARS.musicgenre')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_genres_ordered', to='STARS.project')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('project', 'genre'), ('project', 'position')},
            },
        ),
        migrations.CreateModel(
            name='RankedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('ranked_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='STARS.rankedlist')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('ranked_list', 'position')},
            },
        ),
        migrations.CreateModel(
            name='SongGenresOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_genres_ordered', to='STARS.musicgenre')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_genres_ordered', to='STARS.song')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('song', 'genre'), ('song', 'position')},
            },
        ),
    ]
