# Generated by Django 5.2.5 on 2026-01-22 18:27

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0045_rankedlist_alter_cover_options_alter_review_options_and_more'),
    ]

    operations = [
        TrigramExtension(),
    ]