# Generated by Django 5.2.5 on 2026-01-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0046_enable_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='popularity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='popularity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='musicvideo',
            name='popularity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='outfit',
            name='popularity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='performancevideo',
            name='popularity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='podcast',
            name='popularity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='popularity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='popularity_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
