# Generated by Django 5.2.5 on 2026-01-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0047_cover_popularity_score_event_popularity_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_performance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
