# Generated by Django 5.2.5 on 2026-01-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0048_event_is_performance_alter_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('AWARD_SHOW', 'Award Show'), ('TOUR', 'Tour'), ('FESTIVAL', 'Festival'), ('TV_SHOW', 'TV Show'), ('LIVE_SESSION', 'Live Session'), ('RESIDENCY', 'Residency'), ('OTHER', 'Other'), ('STANDALONE_PERFORMANCE', 'Stand-alone Performance')], db_index=True, default='OTHER', max_length=25),
        ),
    ]
