# Generated by Django 5.2.5 on 2026-01-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0049_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('AWARD_SHOW', 'Award Show'), ('TOUR', 'Tour'), ('FESTIVAL', 'Festival'), ('TV_SHOW', 'TV Show'), ('LIVE_SESSION', 'Live Session'), ('RESIDENCY', 'Residency'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=25),
        ),
    ]
