# Generated by Django 5.2.5 on 2026-01-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0050_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, default='2024-01-01'),
            preserve_default=False,
        ),
    ]
