# Generated by Django 5.2.5 on 2026-01-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0051_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_performance',
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
