# Generated by Django 5.2.5 on 2026-01-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0053_cover_reviews_count_0_5_cover_reviews_count_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
