# Generated by Django 5.2.5 on 2026-01-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0056_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='length',
            field=models.IntegerField(default=0),
        ),
    ]
