# Generated by Django 5.2.5 on 2026-01-31 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0057_alter_project_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='since',
        ),
    ]
