# Generated by Django 5.2.5 on 2026-01-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0058_remove_podcast_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
