# Generated by Django 5.2.5 on 2026-02-04 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0059_alter_podcast_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_series_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='musicvideo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='music_videos_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='outfit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='performancevideo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_videos_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcast',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='podcasts_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
