# Generated by Django 5.2.5 on 2026-02-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0060_event_user_eventseries_user_musicvideo_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO', 'Video'), ('GIF', 'Gif')], default='TEXT', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
