# Generated by Django 5.2.5 on 2026-02-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0061_message_media_url_message_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='star_average',
            field=models.FloatField(default=0),
        ),
    ]
