# Generated by Django 5.2.5 on 2026-02-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0062_artist_star_average'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songartist',
            options={},
        ),
    ]
