# Generated by Django 5.2.5 on 2026-02-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0063_alter_songartist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectartist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectsong',
            options={},
        ),
    ]
