# Generated by Django 5.2.5 on 2026-02-15 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0065_alter_projectartist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectartist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectsong',
            options={},
        ),
    ]
