# Generated by Django 5.2.5 on 2026-02-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0066_alter_projectartist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectartist',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='projectsong',
            options={'ordering': ['disc_number', 'position']},
        ),
        migrations.AlterModelOptions(
            name='songartist',
            options={'ordering': ['position']},
        ),
    ]
