# Generated by Django 5.2.5 on 2026-02-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STARS', '0067_alter_projectartist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picture_is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='picture_is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
